{
 "title": "mp-otel-demo-dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Store front end requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(duration_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(runtime_cpython_cpu_time{service_name=\"$service\"})",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Product recommendations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter{recommendation_type=\"catalog\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(runtime_cpython_memory{service_name=\"$service\"} / 1024 / 1024)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(calls{service_name=\"$service\"}[$__interval]))",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  }
 ]
}